### ISSUE TITLE
I have a problem.

### ISSUE THREAD

**Issue by ElPresidentePro** [shanebrowncs/Trade-Assistant#4]
A few days ago I stopped working this file I only returns the number 0 you know fix as you please do me much needed.

Name: cost.php

<?php
$item = $_GET['item'];
$item = str_replace("\"", "", $item);
$item = str_replace("\'", "", $item);
$item = str_replace(" ", "%20", $item);
$item = str_replace("\", "", $item);
@include_once ("set.php");
$rs = mysql_query("SELECT \* FROM items WHERE name='$item'");
if(mysql_num_rows($rs) > 0) {
    $row = mysql_fetch_array($rs);
    if(time()-$row["lastupdate"] < 604800) die($row["cost"]);
}
$link = "http://steamcommunity.com/market/priceoverview/?currency=1&appid=730&market_hash_name=".$item;
$string = file_get_contents($link);
$obj = json_decode($string);
if($obj->{'success'} == "0") die("notfound");
$lowest_price = $obj->{'lowest_price'};
for($i = 5; $i < strlen($lowest_price); $i++) {
    $lowest_price[$i-5] = $lowest_price[$i];
}
$lowest_price[strlen($lowest_price)] = 0;
$lowest_price = (float)($lowest_price);
mysql_query("DELETE FROM items WHERE name='$item'");
mysql_query("INSERT INTO items (`name`,`cost`,`lastupdate`) VALUES ('$item','$lowest_price','".time()."')");
echo $lowest_price;
?>

**Comment by ElPresidentePro** [comment]
what is a problem?

**Comment by ElPresidentePro** [comment]
http://88.27.57.247/firecsgo.ru/cost.php?item=Chroma%202%20Case%20Key you can see here!

**Comment by shanebrowncs** [comment]
Hi, if you are still curious on getting this to work I have my thoughts below:

I'm not really sure what you are trying to do with the for loop near the end but If you are just trying to get the lowest_price as a floating point value then you can use the code below. 

I removed the for loop as it's adding the 5th index of the string to the very beginning. 19.42 is changed to 419.42. Since you are using USD all valve adds to the price is a $ symbol before the number. I use substr() to remove the symbol, then convert it to a float with the floatval() function you already had there. There was also a syntax error on line 6. You are trying to replace backslashes and aren't accounting for the fact that PHP thinks backslashes are for escape sequences. I fixed this by changing "\" to "\".

PS: mysql functions have been deprecated as of PHP 5.5. If you are using >=5.5 I would recommend using mysqli functions instead.(Ex. mysqli_query())

<?php
    $item = $_GET['item'];
    $item = str_replace("\"", "", $item);
    $item = str_replace("\'", "", $item);
    $item = str_replace(" ", "%20", $item);
    $item = str_replace("\", "", $item);

```
@include_once ("set.php");
$rs = mysql_query("SELECT * FROM items WHERE name='$item'");
if(mysql_num_rows($rs) > 0) {
    $row = mysql_fetch_array($rs);
    if(time()-$row["lastupdate"] < 604800) die($row["cost"]);
}

$link = "http://steamcommunity.com/market/priceoverview/?currency=1&appid=730&market_hash_name=".$item;
$string = file_get_contents($link);
$obj = json_decode($string);
if($obj->{'success'} == "0") die("notfound");

$lowest_price = $obj->{'lowest_price'};
$lowest_price = substr($lowest_price, 1);
$lowest_price[strlen($lowest_price)] = 0;
// No need for casting
$lowest_price = floatval($lowest_price);
mysql_query("DELETE FROM items WHERE name='$item'");
mysql_query("INSERT INTO items (name,cost,lastupdate) VALUES ('$item','$lowest_price','".time()."')");
echo $lowest_price;
```

?>
